### ISSUE TITLE
Default length of 50 is not mentioned on conventional commits website

### ISSUE THREAD

**Issue by JohnMaguire** [crate-ci/committed#143]
https://github.com/crate-ci/committed/blob/3963045ff4801635df253b471a9446972e24c81a/src/config.rs#L42-L44

There is no mention of a 50 character length on: https://www.conventionalcommits.org/en/v1.0.0/

It's not totally clear from this repo's page what standards are enforced. The commit hook in typos simply mentions the above. Perhaps some clarification is all that's needed?

**Comment by epage** [comment]
`committed` checks more than `conventional`.  If that is unclear, please point me to where.

The 50 length limit comes from "general git convention" with [this post](https://chris.beams.io/posts/git-commit/#limit-50) being one example documenting it.  Oh, that link just cargo cults it and doesn't explain why.  Looks like I have to turn to [tpope of VIM fame](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).  Basically, its recommended git commits uses 72 char limit but the subject gits appended to things, like hashes, so its even shorter.

I try to stay shorter but allow exceptions.  Even though I make exception, the enforced limit reminds me to at least ensure the most important words for browsing a log happen before the end.

That is some nuance that is easily lost in an enforcement tool though.    I do need to add a blurb to the pipeline's output to help soften things.  Maybe I should say something there or change the message.

**Comment by JohnMaguire** [comment]
Hey Ed - thanks for the detailed response! I am actually familiar with the 50 character soft limit, and have my editor configured with it as well. Like you, I sometimes stretch the limit a bit (in my case, I had 51 characters.) It's a bit interesting since if you have to add something like `fix(docs): ` in front of the subject, that alone costs 11 characters, leaving you with just 39 to work with.

> `committed` checks more than `conventional`. If that is unclear, please point me to where.

I think that is actually clear - or more accurately, looking at the Github or crates.io page for this project, I see nothing that leads me to believe it's just enforcing Conventional style. I don't really see a clear message of what it _is_ enforcing.

I did find this page, but it also does not mention the default 50-character limit: https://github.com/crate-ci/committed/blob/master/docs/reference.md

I mentioned Conventional since I saw it here, on failure: https://github.com/crate-ci/typos/blob/master/azure-pipelines.yml#L108-L111

Maybe it would be helpful to mention what specifically this project checks on its homepage? This might also be a more comprehensive link than the Conventional docs in the Azure pipeline above.

**Comment by JohnMaguire** [comment]
I should mention that if one of these clarifications sounds like a good plan to you, I can probably go ahead and make a pull request.

**Comment by epage** [comment]
I think another possible change is to make the length of 50 a soft limit and then rely on the general line hard limit past that.  This at least allows a longer word to spill over.

> Maybe it would be helpful to mention what specifically this project checks by default on its homepage

Without just repeating the Reference, I'm unsure of a good way to summarize what we check.  For example, I've considered integrating `typos` into this.

> Or maybe updating reference.md to include defaults? 

Thanks for doing this!

> This might also be a more comprehensive link than the Conventional docs in the Azure pipeline above and/or the CONTRIBUTING file.

In addition to being clarified, the message in the pipeline needs to be softened.  Whenever a contributor comes along and I can comment before the pipeline, I point out that their contribution is more valuable than that check and, depending on their time and git comfort, they can choose from
- Them fixing it
- Me mentoring them in git
- Me fixing when I merge

**Comment by epage** [comment]
Thinking some more on this, an idea I had was
- Make 50 a soft limit
- Add `--dump-config`  to `committed`
- Add the softening message to CI
- Run `committed --dump-config -` to CI so people see what the standards are tailored to the project they are contributing to.  As long as `committed`s config isn't too big, this should be reasonable.

**Comment by epage** [comment]
The current iteration: https://dev.azure.com/crate-ci/crate-ci/_build/results?buildId=1279&view=logs&jobId=c1b99659-8f61-50cd-3b45-84a121acb04b&j=d4cfe60d-5097-5e26-e7da-808cd0fd48ff&t=13010756-fca0-52fa-3b4f-465f2c1e879a

Its a bit noisy because it includes debug information because this is committed running on itself.  Other projects would not carry that forward

**Comment by JohnMaguire** [comment]
> Thinking some more on this, an idea I had was
> 
> * Make 50 a soft limit
> * Add `--dump-config`  to `committed`
> * Add the softening message to CI
> * Run `committed --dump-config -` to CI so people see what the standards are tailored to the project they are contributing to.  As long as `committed`s config isn't too big, this should be reasonable.


I like this a lot. I had a commit message in another project today where I tried for a while to get the subject down to 50 and couldn't quite do it - a soft limit seems like a good idea, and there's prior art for soft/hard limits in the tool already.

I didn't understand the `--dump-config` on first read, but I actually like that a lot. I took a look at the output and here are my first thoughts, and I'm not positive all of this applies to `committed` directly:

- I am reading this backwards.
- There's not a lot of context to what I'm looking at. I know what you're trying to show here, but it's not clear to me that these lines apply to my commit message. This might be more useful to me if I know what I'm supposed to do with it.
- `ignore_author_re = 'dependabot'` this isn't useful to me and as a naive user, isn't clear what it means either. As someone implementing `committed`, this could be useful in understanding why a commit was considered valid even though it didn't pass my rules. It would perhaps be even more clear if I was told whether this applied to the commit at hand or not.
- The rest of the config items have clear names that give me enough context to understand how to fix my commit (as long as I know that this is related to my commit message.)

I really dig this idea, and it seems like a simple way to provide value to both contributors & maintainers. If I were to offer any ideas, some context on whether the commit failed or not, and what to do as a contributor if I'm seeing this message (i.e. if the pipeline failed) could be beneficial.

**Comment by epage** [comment]
Still iterating but here is the latest version: https://dev.azure.com/crate-ci/crate-ci/_build/results?buildId=1286&view=logs&jobId=d4cfe60d-5097-5e26-e7da-808cd0fd48ff&j=d4cfe60d-5097-5e26-e7da-808cd0fd48ff&t=2566c79b-460a-51fc-5977-e2c891e9124d

And again, the TRACE output and the build information won't be in a regular pipeline.  Thats just to help with development of committed itself.

> I am reading this backwards.

This is always a problem with CIs.  Its hard to write meaningful content that works well with reading backwards.  At least with AzDO (and I assume Github Actions), it splits up each step into its own section to read, so you don't get flooded with setup/teardown when reading.

**Comment by JohnMaguire** [comment]
Separating this into a separate job in the pipeline and prefixing with the "Linting commits:" message really helps!

**Comment by epage** [comment]
Yeah, fixing up the names was my next step

**Comment by epage** [comment]
Just did a new release with all of the discussed changes and have updated most of my repos to it (still need to do `typos`)
