### ISSUE TITLE
Capitalization check with non-Latin scripts

### ISSUE THREAD

**Issue by amake** [crate-ci/committed#220]
I work on some projects where the development language uses a non-Latin script, such as Japanese. In these scripts there is no concept of capitalization. When the body of the commit message starts with e.g. `あ` and `subject_capitalization=true` then committed returns an (in my opinion, false) error.

For such projects I can simply turn off the capitalization check. However even in such projects sometimes you *do* have loan words or other Latin strings that start the commit message. So disabling the check is not ideal.

I see that [you use](https://github.com/crate-ci/committed/blob/777fc8c9b020cb87f8adad8db1060989342ee0a5/src/checks.rs#L202) what I understand to be Rust's standard [is_uppercase](https://doc.rust-lang.org/std/primitive.char.html#method.is_uppercase) method. Given the existence of characters that do not have case, I would suggest changing this from `!is_uppercase` to `is_lowercase`. This will allow caseless characters to pass the test.

If there are other concerns such as preventing messages starting with numbers, then I would add explicit checks for those (`is_numeric` etc.).

**Comment by epage** [comment]
Released 1.0 with this fix (realized it was well past time to go 1.x)

**Comment by amake** [comment]
Thanks, and congratulations on 1.0!
