### ISSUE TITLE
Add --style CLI arg

### ISSUE THREAD

**Issue by spwx** [crate-ci/committed#347]
Hello, I think it would be useful to have an command line argument for selecting the style. That way it could be added to a `.pre-commit-config.yaml` and remove the need for a separate `committed.toml` file in some cases.

If it helps, it looks like I got it working here https://github.com/spwx/committed/tree/style_arg. I read your contributing guidelines and it says to open an issue.

Thank you!

**Comment by epage** [comment]
Its intentional that not everything is exposed on the command-line as these should be project properties. We aren't designing exclusively for precommit.
