### ISSUE TITLE
nixpkgs onboarding

### ISSUE THREAD

**Issue by phip1611** [crate-ci/committed#365]
Hi! Is there a reason why this is not in nixpkgs so far but `typos` is?

I can onboard it to nixpkgs, but I can't promise to keep it fresh there.

**Comment by epage** [comment]
Someone else contributed that nixpkg for typos. If someone wants to do it for committed, go for it.

**Comment by PigeonF** [comment]
I have submitted https://github.com/NixOS/nixpkgs/pull/305037

**Comment by ejpcmac** [comment]
`committed` is now available in `nixpkgs`, I think this issue could be closed.
