### ISSUE TITLE
RFE: support for ignoring lines matching a regexp

### ISSUE THREAD

**Issue by scop** [crate-ci/committed#369]
Caveat: haven't actually used committed much at all yet, reporting/requesting this based on docs reference.

The `line_length` option seems to be nice in the sense that it ignores long lines that don't contain a "break" (although I don't know what exactly that means, I hope it's just whitespace) to avoid breaking URLs and the like.

However, it would be nice to be able to ignore certain other lines even if they _do_ contain whitespace. I've used this config with gitlint previously:
```
[ignore-body-lines]
regex = ^(Co-authored-by:|((Closes|Refs|See|-|\*):? )?https?://)
```
... to not demand splitting e.g. the following over multiple lines / not complain about the line length. Some of these would break functionality if split over multiple lines, for others it would just feel awkward.
```
Co-authored-by: long-long-email-address@example.com
Closes: https://example.com/long-long-url
See https://example.com/long-long-url
- https://example.com/long-long-url-in-a-bulleted-list-in-commit-message
* https://example.com/long-long-url-in-another-type-of-bulleted-list-in-commit-message
```

**Comment by epage** [comment]
I'm fine adding something like this if there is a need.

iirc our check only complains if a space exists after `line_length`, so I don't think it'd fire in those cases (the spaces are before `line_length`)

https://github.com/crate-ci/committed/blob/8dc12b5bdbbb20c722919239004a261156b6cd3f/crates/committed/src/checks.rs#L146-L150

**Comment by scop** [comment]
Just got back to this after a long long time, sorry about that.

Looking for a space after the max length works perfect for all realistic use cases I had in mind for this, which is very nice.

The consequence of that though is that it does miss some long lines that would be better off shortened, for example I'd expect an error for:
```
Foo bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar barbarbarbar.
```
... (77 chars > 72) which I think would be better written as:
```
Foo bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar
barbarbarbar.
```

**Comment by epage** [comment]
If there comes up a case where our soft-line-length limits doesn't work out, would love to know and we can re-open this!  Otherwise, I'm closing this for now.
