### ISSUE TITLE
Links in readme don't seem to work

### ISSUE THREAD

**Issue by halkeye** [crate-ci/committed#386]
https://github.com/crate-ci/imperative/blob/master/azure-pipelines.yml goes to 404

**Comment by halkeye** [comment]
I'm guessing it should be https://github.com/crate-ci/azure-pipelines/blob/master/azure-pipelines.yml
should they point there, or copied over into examples type thing?

**Comment by epage** [comment]
Thanks!  Really overlooked updating those!
